# Generated by Django 5.0.9 on 2024-09-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_img', models.URLField()),
                ('description', models.TextField()),
                ('vault_url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='harvesters.harvester')),
            ],
        ),
    ]
