# Generated by Django 5.0.9 on 2024-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('related_to', models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime'), ('none', 'None')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mangavault',
            name='category',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Manhua', 'Manhua'), ('Comics', 'Comics'), ('none', 'None')], default='Manga', max_length=10),
        ),
        migrations.AddField(
            model_name='mangavault',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mangavault',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
