# Generated by Django 5.0.9 on 2024-09-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangavault', '0003_alter_mangagenre_title_alter_mangavault_cover_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangagenre',
            name='related_to',
            field=models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime'), ('both', 'Both'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
